### ISSUE TITLE
replace the install --disk flag with --firstdisk

### ISSUE THREAD

**Issue by cleeistaken** [maxiepax/go-via#5]
The --disk flag does not work on the newer hosts because the disks have unique ID. Using the --firstdisk flag solves this issue. 

Ref. https://community.broadcom.com/vmware-cloud-foundation/discussion/kickstart-installation-how-to-define-disk

**Comment by maxiepax** [comment]
Depending on hardware vendor, and how it handles "firstdisk", you may need to use the "custom ks.cfg" feature described in the Help section. You can modify the ks.cfg either per Group, or per Host.

If you have a HPE G10+ or later server, i've found that modifying the boot settings to have the NS204i as first in the boot order, and using F12 to trigger PXE boot makes it present the NS204i as "firstdisk".

If you have a Dell 15G server or later, you can modify the ks.cfg to specifically point to the BOSS card by entering "install --ignoressd --firstdisk="DELLBOSS VD" --overwritevmfs"

Since all vendors handle this entirelly different, i can choose to either have the code very generic to "suite all", and have the option to simply modify the ks.cfg, or try to gather all hardware vendors "boot disk solutions" and add them to one very long list.

For now i hope it's okey that it's left generic with the option to customise this to suite the purchased hardware :)
